# Generated by Django 5.2.6 on 2025-11-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="contont",
            new_name="content",
        ),
    ]
