# Generated by Django 5.2.6 on 2025-11-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0002_rename_contont_post_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
